
POST http://localhost:3000/reports
content-type: application/json

{
    "price":51011,
    "make":"ferrari",
    "model":"cheorn",
    "year":2000,
    "lng":0,
    "lat":0,
    "mileage":100
}

### Patch
PATCH http://localhost:3000/reports/2
content-type:application/json

{
    "approved":false
}