
POST http://localhost:3000/reports
content-type: application/json

{
    "price":510,
    "make":"nano",
    "model":"cheorn",
    "year":2000,
    "lng":0,
    "lat":0,
    "mileage":1010
}

### Patch
PATCH http://localhost:3000/reports/9
content-type:application/json

{
    "approved":false
}